site_name: Wiki1
site_author: Site Fake
site_url: https://jelkinsp.github.io/wiki
nav:
  - Introduction: 'index.md'

theme:
  name: material
  palette:
    primary: 'blue grey'
    accent: 'light blue'

repo_name: jelkinsp-acciona/wiki
repo_url: https://jelkinsp.github.io/wiki
